export const projects = [
  {
    id: crypto.randomUUID(),
    title: 'NYT Connections Archive',
    description: 'My most recent project was built for my friends after we became obsessed with the daily NYT Connections Puzzle. I wanted to make them a redesigned version, complete with the entire archive of Connections puzzles for them to complete. This is my most robust project yet, complete with scripts for daily database updates, utilizing local storage API for user game data, Framer Motion for clean animations, API routes for different puzzle pages, and responsive design for all devices.',
    type: 'Project',
    link:'https://connections-archive.vercel.app/',
    stack: ['Next.js', 'React', 'TypeScript', 'TailwindCSS', 'Framer Motion','MongoDB', 'Python', 'Design'],
  },
  {
    id: crypto.randomUUID(),
    title: 'Growthware',
    description: 'Joining Growthware was my next opportunity to do client facing, professional work. Growthware is a start-up making tools for small businesses. I built out their website templates, adding pages for client portfolios, services, work showcases, and a merchandise offering. SEO improvement was a major focus as well.',
    type: 'Work',
    stack: ['React', 'TypeScript', 'TailwindCSS', 'SEO', 'Yext CMS', 'Design'],
  },
  {
    id: crypto.randomUUID(),
    title: 'Bluebonnet Data',
    description: 'To begin gaining experience coding on a team, I joined Bluebonnet - an organization offering technical support and resources to progressive campaigns. My first experience was the Data Fellowship, where I helped a city mayor analyze data gathered from a community survey. Most recently, I joined a team building a phone banking tool to get volunteers in North Carolina for the 2024 Presidential Election. The tool ended up being used by a large team of volunteers, and reached 6,000+ people.',
    type: 'Volunteering',
    stack: ['React', 'TypeScript', 'TailwindCSS', 'Python', 'Numpy', 'Seaborn'],
  },
  {
    id: crypto.randomUUID(),
    title: 'NFL Radar Charts 2.0',
    description: 'A complete modernization and redesign of my first project. After learning the powers of React, I rebuilt version 2.0 with a proper database, API routes, modern tooling in Next.js, and a handsome new look.',
    type: 'Project',
    link:'https://nfl-radar-charts2-0.vercel.app/chart-builder',
    stack: ['Next.js', 'React', 'TypeScript', 'TailwindCSS','Supabase', 'Design'],
  },
  {
    id: crypto.randomUUID(),
    title: 'NFL Radar Charts',
    description: 'My first original project idea! After seeing a radar chart of two NFL teams, I had the idea to make a tool capable of generating a similar chart, but with the ability to compare teams dating back to 2002.',
    type: 'Project',
    link:'https://nflradarcharts.pythonanywhere.com/',
    stack: ['JavaScript', 'HTML', 'CSS', 'Python', 'Flask', 'Design'],
  },
]