import { ABeeZee, Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const abeezee = ABeeZee({ subsets: ["latin"], weight: ['400'] });

export const metadata = {
  title: "Dominic Santini | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={abeezee.className}>{children}</body>
    </html>
  );
}
