import { ABeeZee, Inter } from "next/font/google";
import "./globals.css";
import { PageContextProvider } from "./context/pageContext";

const abeezee = ABeeZee({ subsets: ["latin"], weight: ['400'] });

export const metadata = {
  title: "Dominic Santini | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={abeezee.className}>
      <PageContextProvider>  
        <body>{children}</body>
      </PageContextProvider>
    </html>
  );
}
